select current_database();
select * from customer 
limit 20;

-- Total revenue generated by male vs female
select gender, SUM(purchase_amount) as revenue
from customer 
group by gender;

--customer that got a discount but still spent more than average
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)from customer);

-- top 5 products with highest review_rating
select item_purchased, AVG(review_rating) as "Average_review_rating"
from customer c 
group by c.item_purchased 
order by avg(review_rating) desc 
limit 5;

--Compare the average Purchase amounts and standard express shipping
select shipping_type, ROUND(AVG(purchase_amount),2) 
from customer 
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Do subcribed customers spend more?
select subscription_status, 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Top 5 purchased products with discount applied
select item_purchased,
ROUND(100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end )/COUNT(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

--Segmenting customers into new, returning and loyal based on their total number of purchases
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer

)
select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment

--Top 3 products from each category
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased 
)
select item_rank, item_purchased, total_orders 
from item_counts 
where item_rank <= 3;

--are repeat buyers (more than 5 previous purchases)also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Revenue by age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;

select version();